# Generated by Django 5.1.6 on 2025-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="instagram",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="linkedin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="snapchat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
