# Generated by Django 5.1.6 on 2025-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0002_appuser_instagram_appuser_linkedin_appuser_snapchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="cover_picture",
            field=models.ImageField(blank=True, null=True, upload_to="cover_pics/"),
        ),
    ]
