# Generated by Django 5.1.6 on 2025-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardlisting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardlisting",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardlisting",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="boardlisting",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
