services:
  - type: web
    name: campus-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd campus_backend
      pip install -r requirements.txt
      mkdir -p static media staticfiles
      export DJANGO_SETTINGS_MODULE=campus_backend.settings
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: cd campus_backend && gunicorn --worker-class=uvicorn.workers.UvicornWorker --workers=4 --bind=0.0.0.0:$PORT campus_backend.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "campus_backend.settings"
      - key: PYTHONPATH
        value: "/opt/render/project/src/campus_backend"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: campus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: campus-redis
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web
          name: campus-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: campus-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: STATIC_ROOT
        value: "/opt/render/project/src/campus_backend/staticfiles"
      - key: MEDIA_ROOT
        value: "/opt/render/project/src/campus_backend/media"

  - type: web
    name: campus-frontend
    env: static
    buildCommand: cd campus_frontend && npm install && npm run build
    staticPublishPath: ./campus_frontend/dist
    envVars:
      - key: REACT_APP_ENV
        value: "production"
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: campus-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: REACT_APP_WS_URL
        fromService:
          type: web
          name: campus-backend
          envVarKey: RENDER_EXTERNAL_URL
          format: wss://${value}

  - type: redis
    name: campus-redis
    ipAllowList: []
    plan: free

databases:
  - name: campus-db
    plan: free 