# Generated by Django 5.1.6 on 2025-04-05 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BOOKS", "Books"),
                            ("SUBLETS", "Sublets"),
                            ("ROOMMATES", "Roommates"),
                            ("RIDESHARE", "Rideshare and Travel"),
                            ("EVENTS", "Events"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[("Poor", "Poor"), ("Fair", "Fair"), ("Good", "Good")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="listing_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookListing",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="listings.listing",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("edition", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "course_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pickup_location", models.CharField(max_length=255)),
            ],
            bases=("listings.listing",),
        ),
        migrations.CreateModel(
            name="EventsAndOther",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="listings.listing",
                    ),
                ),
            ],
            bases=("listings.listing",),
        ),
        migrations.CreateModel(
            name="RideShare",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="listings.listing",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                (
                    "mode_of_travel",
                    models.CharField(
                        choices=[
                            ("TRAIN", "Train"),
                            ("PLANE", "Plane"),
                            ("AUTOMOBILE", "Automobile"),
                            ("BUS", "Bus"),
                            ("OTHER", "Other"),
                        ],
                        default="Automobile",
                        max_length=255,
                    ),
                ),
                ("date_of_travel", models.DateTimeField(blank=True, null=True)),
            ],
            bases=("listings.listing",),
        ),
        migrations.CreateModel(
            name="Roommates",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="listings.listing",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("First Year", "First Year"),
                            ("Second Year", "Second Year"),
                            ("Third Year", "Third Year"),
                            ("Fourth Year", "Fourth Year"),
                            ("Fifth Year or Above", "Fifth Year or Above"),
                            ("Graduate Student", "Graduate Student"),
                        ],
                        default="First Year",
                        max_length=255,
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-binary"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="prefer_not_to_say",
                        max_length=255,
                    ),
                ),
                ("program", models.CharField(max_length=255)),
                (
                    "social_media",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("additional_information", models.TextField(blank=True, null=True)),
            ],
            bases=("listings.listing",),
        ),
        migrations.CreateModel(
            name="SubletListing",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="listings.listing",
                    ),
                ),
                ("house_address", models.TextField()),
                ("rooms", models.IntegerField()),
                ("length_of_stay", models.CharField(max_length=255, null=True)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("First Year", "First Year"),
                            ("Second Year", "Second Year"),
                            ("Third Year", "Third Year"),
                            ("Fourth Year", "Fourth Year"),
                            ("Fifth Year or Above", "Fifth Year or Above"),
                            ("Graduate Student", "Graduate Student"),
                        ],
                        default="First Year",
                        max_length=255,
                    ),
                ),
            ],
            bases=("listings.listing",),
        ),
    ]
